name: Build and Test

on:
  workflow_call:
    outputs:
      snap:
        description: "Filename of the built snap"
        value: ${{ jobs.main.outputs.snap }}

jobs:
  main:
    runs-on: ubuntu-latest
    outputs:
      snap: ${{ steps.snapcraft.outputs.snap }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build snap locally
        uses: snapcore/action-build@v1
        id: snapcraft
        with:
          snapcraft-channel: 7.x/candidate

      - name: Upload locally built snap artifact
        uses: actions/upload-artifact@v3
        with:
          name: local-${{ steps.snapcraft.outputs.snap }}
          path: ${{ steps.snapcraft.outputs.snap }}

      - name: Install snap & invoke parca
        run: |
          sudo snap install --dangerous ${{ steps.snapcraft.outputs.snap }}
          parca --version

      - name: Start Parca and ensure API is up
        run: |
          # Start the service packaged with the snap
          sudo snap start parca

          # Check we can hit the main web endpoint
          curl http://localhost:7070/

          # Check we can hit the metrics endpoint
          curl http://localhost:7070/metrics
